apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-world-pod
spec:
  replicas: 2
  template:
    metadata:
      labels: # labels to select/identify the deployment
        app: hello-world  
    spec:     # pod spec                  
      containers: 
      - name: hello-world 
        image: ibmdocker8te/node-js:v2 # image we pushed in your contaieer registry
        ports:
        - name: nodejs-port
          containerPort: 3000
